
/*
VIM macro to extract function name from error string.
Just load with e.g. "qy and run with @q
/symbol
eld^xeld$yypkve~VUiPFNAPROC,IOPENGL_UNCFUNC(JA)j^
*/

OPENGL_FUNC(PFNGLGETSHADERIVPROC, glGetShaderiv)
OPENGL_FUNC(PFNWGLCREATECONTEXTATTRIBSARBPROC, wglCreateContextAttribsARB)
OPENGL_FUNC(PFNGLGETPROGRAMIVPROC, glGetProgramiv)
OPENGL_FUNC(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog)
OPENGL_FUNC(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog)
OPENGL_FUNC(PFNGLCREATEPROGRAMPROC, glCreateProgram)
OPENGL_FUNC(PFNGLCREATESHADERPROC, glCreateShader)
OPENGL_FUNC(PFNGLSHADERSOURCEPROC, glShaderSource)
OPENGL_FUNC(PFNGLCOMPILESHADERPROC, glCompileShader)
OPENGL_FUNC(PFNGLATTACHSHADERPROC, glAttachShader)
OPENGL_FUNC(PFNGLLINKPROGRAMPROC, glLinkProgram)
OPENGL_FUNC(PFNGLACTIVETEXTUREPROC, glActiveTexture)
OPENGL_FUNC(PFNGLGENVERTEXARRAYSPROC, glGenVertexArrays)
OPENGL_FUNC(PFNGLBINDVERTEXARRAYPROC, glBindVertexArray)
OPENGL_FUNC(PFNGLGENBUFFERSPROC, glGenBuffers)
OPENGL_FUNC(PFNGLBINDBUFFERPROC, glBindBuffer)
OPENGL_FUNC(PFNGLBUFFERDATAPROC, glBufferData)
OPENGL_FUNC(PFNGLGETATTRIBLOCATIONPROC, glGetAttribLocation)
OPENGL_FUNC(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray)
OPENGL_FUNC(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer)
OPENGL_FUNC(PFNGLMAPBUFFERPROC, glMapBuffer)
OPENGL_FUNC(PFNGLUNMAPBUFFERPROC, glUnmapBuffer)
OPENGL_FUNC(PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation)
OPENGL_FUNC(PFNGLUNIFORM1IVPROC, glUniform1iv)
OPENGL_FUNC(PFNGLUNIFORM1FVPROC, glUniform1fv)
OPENGL_FUNC(PFNGLUNIFORMMATRIX4FVPROC, glUniformMatrix4fv)
OPENGL_FUNC(PFNGLUNIFORMMATRIX3FVPROC, glUniformMatrix3fv)
OPENGL_FUNC(PFNGLUNIFORM4FVPROC, glUniform4fv)
OPENGL_FUNC(PFNGLUNIFORM3FVPROC, glUniform3fv)
OPENGL_FUNC(PFNGLUNIFORM2FVPROC, glUniform2fv)
OPENGL_FUNC(PFNGLUNIFORM1IPROC, glUniform1i)
OPENGL_FUNC(PFNGLUSEPROGRAMPROC, glUseProgram)
OPENGL_FUNC(PFNGLGENFRAMEBUFFERSPROC, glGenFramebuffers)
OPENGL_FUNC(PFNGLBINDFRAMEBUFFERPROC, glBindFramebuffer)
OPENGL_FUNC(PFNGLFRAMEBUFFERTEXTUREPROC, glFramebufferTexture)
OPENGL_FUNC(PFNGLDRAWBUFFERSPROC, glDrawBuffers)
OPENGL_FUNC(PFNGLCHECKFRAMEBUFFERSTATUSPROC, glCheckFramebufferStatus)
OPENGL_FUNC(PFNGLCLAMPCOLORPROC, glClampColor)
OPENGL_FUNC(PFNGLDELETEFRAMEBUFFERSPROC, glDeleteFramebuffers)

